void board_layout();
void getTilesAttr();
void displayTiles();
void freeTilesMemory();
void *getBoardAttr(void *args);
void attrProperty(int i,int randomIndex);
void attrOffice(int i,int randomIndex);
void attrAirport(int i,int randomIndex);
void attrLuck(int i,int randomIndex);
void attrPrison(int i,int randomIndex);
void update_file_player_details(const char *p_name, const char *mod_value, const char *mod_column);
void *displayBoard(void *args);
void make_negative_double(double *num);